# --- ec2/variables
variable "instance_count" {}
variable "instance_type" {}
variable "private_subnets" {}
variable "vol_size" {}
variable "lb_target_group_arn" {}
variable "private_sg" {}
variable "key_name" {}
variable "public_key_path" {}
variable "aws_nat_gateway" {}
